apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: quay.io/jcho0/observability-operator
  newTag: 0.0.23
commonAnnotations:
  package-operator.run/phase: operator
resources:
- ../../operator/
