name: build-and-publish

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag. Defaults to 0.0.23'
        required: false 
        default: "0.0.23"
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag || '0.0.23' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make Tools
        run: make tools

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Publish
        run: ./hack/build.sh ${{ env.TAG }}
